import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SearchFrom from '../components/seachForm'
import Header from '../components/header';
import { MetaMaskProvider } from 'metamask-react';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Alchemy nfts gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
      </Head>

      <MetaMaskProvider>
        <Header />
      </MetaMaskProvider>

      <main className={styles.main}>
        <div className={styles.card}>
          <SearchFrom />
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          @copyright Powered by Ayden Lee
        </a>
      </footer>
    </div>
  )
}
